name: Test versioning

on: push

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bump version and push tag
      id: versioning
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: fabricepipart
        WITH_V: ${{ github.ref != 'refs/heads/master' }}
    - name: Echo version
      env:
        version: ${{ steps.versioning.outputs.new_tag }}
      run: |
        echo $version
